### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by pawelmorawiecki** [marcellodebernardi/loss-landscapes#1]
Hi,

It there any way to run loss_landscapes.random_plane on GPU? I tried to run it on Google's Colab with GPU but got an error "
RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float"

**Comment by ddavidse** [comment]
This is working fine for me, when I adjusted the rest of my code for GPU the loss_landscapes package gained a massive speedup automatically

**Comment by johncava** [comment]
Hi,

I have a similar problem. I am trying to use a pretrained resnet, and I tried putting them into cuda, but I am getting an error specifically from loss_landscapes/model_interface/model_parameters.py. This is [my code](https://gist.github.com/johncava/0212cffedb576f1401942230e3e4d2fa). 

But I get this error:

`Traceback (most recent call last):                                              
  File "resnet.py", line 165, in <module>                                       
    loss_data_fin = random_plane(model_final,metric,10,STEPS,normalization='filter',deepcopy_model=True)
  File "/home/jcava/.conda/envs/pytorch-1.30-gpu/lib/python3.7/site-packages/loss_landscapes/main.py", line 298, in random_plane
    start_point.sub_(dir_one)                                                   
  File "/home/jcava/.conda/envs/pytorch-1.30-gpu/lib/python3.7/site-packages/loss_landscapes/model_interface/model_parameters.py", line 115, in sub_
    self.parameters[idx] -= vector[idx]                                         
RuntimeError: expected device cuda:0 but got device cpu`

**Comment by MasanoriYamada** [comment]
I replaced the function in loss_landscapes/model_interface/model_parameters.py with the following and it worked on the GPU.
My environment is torch==1.6.0


```
def rand_u_like(example_vector: ModelParameters) -> ModelParameters:
    """
    Create a new ModelParameters object of size and shape compatible with the given
    example vector, such that the values in the ModelParameter are uniformly distributed
    in the range [0,1].
    :param example_vector: defines by example the size and shape the new vector will have
    :return: new vector with uniformly distributed values
    """
    new_vector = []

    for param in example_vector:
        new_vector.append(torch.rand(size=param.size(), dtype=example_vector[0].dtype).to(param.device))

    return ModelParameters(new_vector)


def rand_n_like(example_vector: ModelParameters) -> ModelParameters:
    """
    Create a new ModelParameters object of size and shape compatible with the given
    example vector, such that the values in the ModelParameter are normally distributed
    as N(0,1).
    :param example_vector: defines by example the size and shape the new vector will have
    :return: new vector with normally distributed values
    """
    new_vector = []

    for param in example_vector:
        new_vector.append(torch.randn(size=param.size(), dtype=example_vector[0].dtype).to(param.device))

    return ModelParameters(new_vector)

```

**Comment by ansleepykid** [comment]
how can you change the egg

**Comment by ansleepykid** [comment]
is there any method to use cuda

**Comment by petteriTeikari** [comment]
Do the developers (@marcellodebernardi ) have any time to update that nice tweak by @MasanoriYamada so that the GPU option would work straight from pip install? Would simplify the use of this nice module across organization (noticed yes the disclaimer of this not being production code) :)

**Comment by 916906445** [comment]
> Hi,
> 
> I have a similar problem. I am trying to use a pretrained resnet, and I tried putting them into cuda, but I am getting an error specifically from loss_landscapes/model_interface/model_parameters.py. This is [my code](https://gist.github.com/johncava/0212cffedb576f1401942230e3e4d2fa).
> 
> But I get this error:
> 
> `Traceback (most recent call last): File "resnet.py", line 165, in <module> loss_data_fin = random_plane(model_final,metric,10,STEPS,normalization='filter',deepcopy_model=True) File "/home/jcava/.conda/envs/pytorch-1.30-gpu/lib/python3.7/site-packages/loss_landscapes/main.py", line 298, in random_plane start_point.sub_(dir_one) File "/home/jcava/.conda/envs/pytorch-1.30-gpu/lib/python3.7/site-packages/loss_landscapes/model_interface/model_parameters.py", line 115, in sub_ self.parameters[idx] -= vector[idx] RuntimeError: expected device cuda:0 but got device cpu`

I am having the same problem as you, have you solved your problem yet?If so how was it resolved?

**Comment by ansleepykid** [comment]
Sorry, I didn't solve the problem.
&nbsp;


603220383
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月15日(星期三) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [marcellodebernardi/loss-landscapes] GPU support? (#1)














  
Hi,
 
I have a similar problem. I am trying to use a pretrained resnet, and I tried putting them into cuda, but I am getting an error specifically from loss_landscapes/model_interface/model_parameters.py. This is my code.
 
But I get this error:
 
Traceback (most recent call last): File "resnet.py", line 165, in <module&gt; loss_data_fin = random_plane(model_final,metric,10,STEPS,normalization='filter',deepcopy_model=True) File "/home/jcava/.conda/envs/pytorch-1.30-gpu/lib/python3.7/site-packages/loss_landscapes/main.py", line 298, in random_plane start_point.sub_(dir_one) File "/home/jcava/.conda/envs/pytorch-1.30-gpu/lib/python3.7/site-packages/loss_landscapes/model_interface/model_parameters.py", line 115, in sub_ self.parameters[idx] -= vector[idx] RuntimeError: expected device cuda:0 but got device cpu
  
I am having the same problem as you, have you solved your problem yet?If so how was it resolved?
